"use client";

import { Kanit, Orbitron } from "next/font/google";
import { App } from "./app";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// better to read
// const chakraPetch = Chakra_Petch({
//   subsets: ["latin"],
//   weight: ["300", "400", "500", "600", "700"], // Available weights for Chakra Petch
//   display: "swap",
//   variable: "--font-chakra-petch",
// });

// better to read
const kanit = Kanit({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All weights available
  display: "swap",
  variable: "--font-kanit",
});

// hard to read but very cool: use for headings
export const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"], // Orbitron has all these weights
  display: "swap",
  variable: "--font-orbitron",
});

const globalFontFamily = `${kanit?.style?.fontFamily}, Verdana, "Helvetica Neue", Arial, sans-serif`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        {/* <link
          href="https://fonts.googleapis.com/css?family=Jura:300,400,500,600,700&display=swap"
          rel="stylesheet"
        ></link> */}
      </head>

      <body
        style={{
          fontFamily: globalFontFamily,
          fontSize: "16px",
          margin: 0,
          padding: 0,
          boxSizing: "border-box",
        }}
      >
        <App>{children}</App>
      </body>
    </html>
  );
}
